### ISSUE TITLE
Errors using build in version 1.10.1 

### ISSUE THREAD

**Issue by adnichols** [swipely/docker-api#109]
Starting in version 1.10.1 I see the following in docker running in debug mode when trying to perform a build command against Docker version 0.8.1:

```
2014/03/17 19:28:06 POST /v1.10/build?rm=false
[error] api.go:998 Error: Multipart upload for build is no longer supported. Please upgrade your docker client.
[error] api.go:105 HTTP Error: statusCode=500 Multipart upload for build is no longer supported. Please upgrade your docker client.
```

If I revert to 1.9.x of the docker-api client this problem stops. 

This error doesn't seem to occur when operating against Docker 0.9 however given the minor version increment of the gem from 1.9.x to 1.10.x I would have expected it to be backward compatible. This makes moving forward to 1.10.x difficult as it means anyone using the new version has to have docker >= 0.9

Thoughts on why this may be?
